MalaFirmaTaxi/Controllers/SamochodyController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MalaFirmaTaxi.Data;
using MalaFirmaTaxi.Models;
using Microsoft.AspNetCore.Http;

namespace MalaFirmaTaxi.Controllers
{
	public class SamochodyController : Controller
	{
		private readonly TaxiContext _context;

		public SamochodyController(TaxiContext context)
		{
			_context = context;
		}

		// GET: Samochody
		public async Task<IActionResult> Index()
		{
			return View(await _context.Samochody.ToListAsync());
		}

		// GET: Samochody/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var samochod = await _context.Samochody
				.SingleOrDefaultAsync(m => m.ID == id);
			if (samochod == null)
			{
				return NotFound();
			}

			return View(samochod);
		}

		// GET: Samochody/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Samochody/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("ID,Marka,Model,LiczbaMiejsc,Koszt1Km")] Samochod samochod)
		{
			if (!ModelState.IsValid) 
				return View(samochod);

			if (SamochodExists(samochod))
			{
				HttpContext.Session.SetString("AlertText", "W bazie danych istnieje już podany samochód");
				return View(samochod);
			}

			_context.Add(samochod);
			await _context.SaveChangesAsync();
			HttpContext.Session.SetString("DialogText", "Pomyślnie zapisano nowy samochód");

			if(HttpContext.Session.GetString("KierowcaID")!=null)
				return RedirectToAction("Edit", "Kierowcy", new { id = int.Parse(HttpContext.Session.GetString("KierowcaID")) });

			return RedirectToAction("Create", "Kierowcy");
		}

		// GET: Samochody/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var samochod = await _context.Samochody.SingleOrDefaultAsync(m => m.ID == id);
			if (samochod == null)
			{
				return NotFound();
			}
			return View(samochod);
		}

		// POST: Samochody/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("ID,Marka,Model,LiczbaMiejsc,Koszt1Km")] Samochod samochod)
		{
			if (id != samochod.ID)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(samochod);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!SamochodExists(samochod.ID))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}

				HttpContext.Session.SetString("DialogText", "Pomyślnie zapisano zmiany danych samochodu");
				if (HttpContext.Session.GetString("KierowcaID") != null)
					return RedirectToAction("Edit", "Kierowcy", new { id = int.Parse(HttpContext.Session.GetString("KierowcaID")) });

				return RedirectToAction("PanelKierowcy", "Kierowcy");
			}
			return View(samochod);
		}

		// GET: Samochody/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var samochod = await _context.Samochody
				.SingleOrDefaultAsync(m => m.ID == id);
			if (samochod == null)
			{
				return NotFound();
			}

			return View(samochod);
		}

		// POST: Samochody/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var samochod = await _context.Samochody.SingleOrDefaultAsync(m => m.ID == id);
			_context.Samochody.Remove(samochod);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool SamochodExists(int id)
		{
			return _context.Samochody.Any(e => e.ID == id);
		}

		private bool SamochodExists(Samochod samochod)
		{
			return _context.Samochody.Any(e => e.Marka == samochod.Marka && e.Model == samochod.Model && e.Koszt1Km == samochod.Koszt1Km);
		}
	}
}

MalaFirmaTaxi/Controllers/TransakcjeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MalaFirmaTaxi.Data;
using MalaFirmaTaxi.Models;
using Microsoft.AspNetCore.Http;

namespace MalaFirmaTaxi.Controllers
{
    public class TransakcjeController : Controller
    {
        private readonly TaxiContext _context;

        public TransakcjeController(TaxiContext context)
        {
            _context = context;    
        }

        // GET: Transakcje
        public async Task<IActionResult> Index()
        {
            var taxiContext = _context.Transakcje.Include(t => t.Kierowca).Include(t => t.Lokalizacja).Include(t => t.Zlecenie);
            return View(await taxiContext.ToListAsync());
        }

        // GET: Transakcje/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transakcja = await _context.Transakcje
                .Include(t => t.Kierowca)
                .Include(t => t.Lokalizacja)
                .Include(t => t.Zlecenie)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (transakcja == null)
            {
                return NotFound();
            }

            return View(transakcja);
        }

        // GET: Transakcje/Create
        public IActionResult Create()
        {
            ViewData["KierowcaID"] = new SelectList(_context.Kierowcy, "ID", "FullName");
	        ViewData["LokalizacjaID"] = PopulateLokalizacjaDropDownListOrderedByUlica();

			ViewData["ZlecenieID"] = new SelectList(_context.Zlecenia, "ID", "ID");
            return View();
        }

        // POST: Transakcje/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,KierowcaID,LokalizacjaID,ZlecenieID,StempelCzasu,Rodzaj,Uwagi")] Transakcja transakcja)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transakcja);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["KierowcaID"] = new SelectList(_context.Kierowcy, "ID", "Imie", transakcja.KierowcaID);
            ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Adres", transakcja.LokalizacjaID);
            ViewData["ZlecenieID"] = new SelectList(_context.Zlecenia, "ID", "ID", transakcja.ZlecenieID);
            return View(transakcja);
        }

		// GET: Transakcje/CreateByKierowca
		public IActionResult CreateByKierowca()
		{
			if (HttpContext.Session.GetString("RedirectFromTransakcja") == null)
				HttpContext.Session.SetString("RedirectFromTransakcja", "/Kierowcy/PanelKierowcy");

			if (HttpContext.Session.GetString("KierowcaID") == null || HttpContext.Session.GetString("KierowcaFullName") == null)
			{
				return Redirect("/Kierowcy/Login");
			}

			HttpContext.Session.SetString("RedirectFromLokalizacja", "/Transakcje/CreateByKierowca");
			ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Adres");
		    ViewData["ZlecenieID"] = new SelectList(_context.Zlecenia, "ID", "ID");
		    return View();
	    }

		// POST: Transakcje/CreateByKierowca
		[HttpPost]
	    [ValidateAntiForgeryToken]
	    public async Task<IActionResult> CreateByKierowca([Bind("ID,KierowcaID,LokalizacjaID,ZlecenieID,StempelCzasu,Rodzaj,Uwagi")] Transakcja transakcja)
	    {
		    if (ModelState.IsValid)
		    {
			    _context.Add(transakcja);
			    await _context.SaveChangesAsync();
			    HttpContext.Session.SetString("DialogText", "Utworzono nową transakcję");
				return Redirect(HttpContext.Session.GetString("RedirectFromTransakcja"));
		    }

			ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Adres", transakcja.LokalizacjaID);
		    ViewData["ZlecenieID"] = new SelectList(_context.Zlecenia, "ID", "ID", transakcja.ZlecenieID);
		    return View(transakcja);
	    }

		// GET: Transakcje/CreateAwariaByKierowca
		public IActionResult CreateAwariaByKierowca()
	    {
		    if (HttpContext.Session.GetString("RedirectFromTransakcja") == null)
			    HttpContext.Session.SetString("RedirectFromTransakcja", "/Kierowcy/PanelKierowcy");

		    if (HttpContext.Session.GetString("KierowcaID") == null)
		    {
			    return Redirect("/Kierowcy/PanelKierowcy");
		    }

		    HttpContext.Session.SetString("RedirectFromLokalizacja", "/Transakcje/CreateAwariaByKierowca");
		    ViewData["KierowcaID"] = HttpContext.Session.GetString("KierowcaID");
		    ViewData["LokalizacjaID"] = PopulateLokalizacjaDropDownListOrderedByUlica();
			ViewData["ZlecenieID"] = HttpContext.Session.GetString("ZlecenieID");

			return View();
	    }

		// POST: Transakcje/CreateAwariaByKierowca
		[HttpPost]
	    [ValidateAntiForgeryToken]
	    public async Task<IActionResult> CreateAwariaByKierowca([Bind("ID,KierowcaID,LokalizacjaID,ZlecenieID,StempelCzasu,Rodzaj,Uwagi")] Transakcja transakcja)
	    {
		    if (ModelState.IsValid)
		    {
			    _context.Add(transakcja);
			    await _context.SaveChangesAsync();
			    HttpContext.Session.SetString("DialogText", "Zarejestrowano traksakcję: Awaria. Zaczekaj z pasażerem do czasu przyjazdu kierowcy zastępczego.");
				_context.AddAwaryjnePrzyjecieZleceniaForZlecenie(transakcja.ZlecenieID.Value);
			    return Redirect(HttpContext.Session.GetString("RedirectFromTransakcja"));
		    }

			ViewData["KierowcaID"] = HttpContext.Session.GetString("KierowcaID");
		    ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Adres");
		    ViewData["ZlecenieID"] = HttpContext.Session.GetString("ZlecenieID");
			return View(transakcja);
	    }

	    public IActionResult CreateAktywnyByKierowca()
		{
			if (HttpContext.Session.GetString("KierowcaID") == null)
			{
				return RedirectToAction("PanelKierowcy", "Kierowcy");
			}

			HttpContext.Session.SetString("RedirectFromLokalizacja", "/Transakcje/CreateAktywnyByKierowca");
			ViewData["KierowcaID"] = HttpContext.Session.GetString("KierowcaID");
			ViewData["LokalizacjaID"] = PopulateLokalizacjaDropDownListOrderedByUlica();
			ViewData["ZlecenieID"] = HttpContext.Session.GetString("ZlecenieID");

			return View();
		}

		private SelectList PopulateLokalizacjaDropDownListOrderedByUlica()
		{
			return new SelectList(_context.Lokalizacje.OrderBy(s => s.Ulica), "ID", "Adres");
		}

		[HttpPost]
	    [ValidateAntiForgeryToken]
	    public async Task<IActionResult> CreateAktywnyByKierowca([Bind("ID,KierowcaID,LokalizacjaID,ZlecenieID,StempelCzasu,Rodzaj,Uwagi")] Transakcja transakcja)
	    {
		    if (ModelState.IsValid)
		    {
			    _context.Add(transakcja);
			    await _context.SaveChangesAsync();
			    HttpContext.Session.SetString("DialogText", "Zarejestrowano traksakcję: Aktywny. Witamy na pokładzie!");
			    return RedirectToAction("PanelKierowcy", "Kierowcy");
		    }

		    ViewData["KierowcaID"] = HttpContext.Session.GetString("KierowcaID");
		    ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Adres");
		    ViewData["ZlecenieID"] = HttpContext.Session.GetString("ZlecenieID");
		    return View(transakcja);
	    }

	    public IActionResult CreateNieaktywnyByKierowca()
	    {
		    if (HttpContext.Session.GetString("KierowcaID") == null)
		    {
			    return RedirectToAction("PanelKierowcy", "Kierowcy");
		    }

		    HttpContext.Session.SetString("RedirectFromLokalizacja", "/Transakcje/CreateNieaktywnyByKierowca");
		    ViewData["KierowcaID"] = HttpContext.Session.GetString("KierowcaID");
		    ViewData["LokalizacjaID"] = PopulateLokalizacjaDropDownListOrderedByUlica();
		    ViewData["ZlecenieID"] = HttpContext.Session.GetString("ZlecenieID");

		    return View();
	    }

	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public async Task<IActionResult> CreateNieaktywnyByKierowca([Bind("ID,KierowcaID,LokalizacjaID,ZlecenieID,StempelCzasu,Rodzaj,Uwagi")] Transakcja transakcja)
	    {
		    if (ModelState.IsValid)
		    {
			    _context.Add(transakcja);
			    await _context.SaveChangesAsync();
			    HttpContext.Session.SetString("DialogText", "Zarejestrowano traksakcję: Nieaktywny. Załatw swoje sprawy i szybko wracaj do nas! ");
				return RedirectToAction("PanelKierowcy", "Kierowcy");
			}

		    ViewData["KierowcaID"] = HttpContext.Session.GetString("KierowcaID");
		    ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Adres");
		    ViewData["ZlecenieID"] = HttpContext.Session.GetString("ZlecenieID");
		    return View(transakcja);
	    }

		// GET: Transakcje/Edit/5
		public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transakcja = await _context.Transakcje.SingleOrDefaultAsync(m => m.ID == id);
            if (transakcja == null)
            {
                return NotFound();
            }
            ViewData["KierowcaID"] = new SelectList(_context.Kierowcy, "ID", "Imie", transakcja.KierowcaID);
            ViewData["LokalizacjaID"] = new SelectList(_context.Lokalizacje, "ID", "Miasto", transakcja.LokalizacjaID);
            ViewData["ZlecenieID"] = new SelectList(_context.Zlecenia, "ID", "ID", transakcja.ZlecenieID);
            return View(transakcja);
        }

        // POST: Transakcje/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,KierowcaID,LokalizacjaID,ZlecenieID,StempelCzasu,Rodzaj,Uwagi")] Transakcja transakcja)
        {
            if (id != transakcja.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transakcja);
                    await _context.SaveChangesAsync();
                }

MalaFirmaTaxi/Views/Kierowcy/Create.cshtml
@using Microsoft.AspNetCore.Http
@model MalaFirmaTaxi.Models.Kierowca

@{
	ViewData["Title"] = "Rejestracja";
}

@if (Context.Session.GetString("AlertText") != null)
{
	<div class="alert alert-danger">
		<strong>Błąd:</strong> @Context.Session.GetString("AlertText")
	</div>
	Context.Session.Remove("AlertText");
}
@if (Context.Session.GetString("DialogText") != null)
{
	<div class="alert alert-success">
		<strong>Sukces!</strong> @Context.Session.GetString("DialogText")
	</div>
	Context.Session.Remove("DialogText");
}

<h2>Zarejestruj się</h2>

<form asp-action="Create">
	<div class="form-horizontal">
		<h4>Profil Kierowcy</h4>
		<hr />
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<label class="col-md-2 control-label">Imię</label>
			<div class="col-md-10">
				<input asp-for="Imie" class="form-control" />
				<span asp-validation-for="Imie" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Nazwisko" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="Nazwisko" class="form-control" />
				<span asp-validation-for="Nazwisko" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Samochód</label>
			<div class="col-md-10">
				<a asp-action="Create" asp-controller="Samochody" class="btn btn-default">Dodaj nowy samochód</a>
				<select asp-for="SamochodID" class="form-control" asp-items="ViewBag.SamochodID">
				</select>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Zarejestruj" class="btn btn-success" />
			</div>
		</div>
	</div>
</form>

<div>
	<a asp-action="Login" class="btn btn-default">Wróć do logowania</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MalaFirmaTaxi/Views/Kierowcy/Delete.cshtml
@model MalaFirmaTaxi.Models.Kierowca

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kierowca</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Samochod)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Samochod.Marka)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

MalaFirmaTaxi/Views/Kierowcy/Details.cshtml
@model MalaFirmaTaxi.Models.RelatedViewsModels.KierowcyDetailsData

@{
	ViewData["Title"] = "Szczegóły wybranego kierowcy";
}

<h2>Szczegóły </h2>

<div>
	<h4>Kierowca nr @Model.Kierowca.ID</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>Imię</dt>
		<dd>
			@Html.DisplayFor(model => model.Kierowca.Imie)
		</dd>
		<dt>Nazwisko</dt>
		<dd>
			@Html.DisplayFor(model => model.Kierowca.Nazwisko)
		</dd>
		<dt>Samochód</dt>
		<dd>
			<table class="table">
				<tr>
					<th>Marka</th>
					<th>Model</th>
					<th>Liczba miejsc</th>
					<th>Koszt przejechania 1 km</th>
				</tr>
				<tr>
					<td>
						@Html.DisplayFor(model => model.Kierowca.Samochod.Marka)
					</td>
					<td>
						@Html.DisplayFor(model => model.Kierowca.Samochod.Model)
					</td>
					<td>
						@Html.DisplayFor(model => model.Kierowca.Samochod.LiczbaMiejsc)
					</td>
					<td>
						@Html.DisplayFor(model => model.Kierowca.Samochod.Koszt1Km)
					</td>
				</tr>

			</table>
		</dd>
		<dt>Zlecenia</dt>
		<dd>
			<table class="table">
				<tr>
					<th>Klient</th>
					<th>Start</th>
					<th>Cel</th>
					<th>Koszt</th>
					<th>Liczba osób</th>
					<th></th>
				</tr>
				<tbody>
					@foreach (var item in Model.Zlecenia)
					{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.Klient.FullName)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.LokalizacjaStart.Adres)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.LokalizacjaCel.Adres)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Koszt)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.LiczbaOsob)
						</td>
						<td>
							@Html.ActionLink("Szczegóły", "Details", new { zlecenieID = item.ID })
						</td>
					</tr>
					}
			</table>
		</dd>
	</dl>
</div>
@if (Model.Transakcje != null)
{
	<h3>
		Transakcje powiązane z wybranym zleceniem
	</h3>
	<table class="table">
		<tr>
			<th>Data i godzina</th>
			<th>Lokalizacja</th>
			<th>Kierowca</th>
			<th>Rodzaj transakcji</th>
			<th>Uwagi</th>
		</tr>
		@foreach (var item in Model.Transakcje)
		{
		<tr>
			<td>
				@item.StempelCzasu
			</td>
			<td>
				@item.Lokalizacja.Adres
			</td>
			<td>
				@item.Kierowca.FullName
			</td>
			<td>
				@item.Rodzaj
			</td>
			<td>
				@if (item.Uwagi != null)
					{
					@item.Uwagi
					}
			</td>
		</tr>
		}
	</table>
}
<div>
	<a asp-action="Edit" asp-route-id="@Model.Kierowca.ID">Edytuj</a> |
	<a asp-action="Index">Powrót do listy kierowców</a>
</div>

MalaFirmaTaxi/Views/Kierowcy/Edit.cshtml
@using Microsoft.AspNetCore.Http
@model MalaFirmaTaxi.Models.Kierowca

@{
	ViewData["Title"] = "Edycja";
}

@if (Context.Session.GetString("DialogText") != null)
{
	<div class="alert alert-success">
		<strong>Sukces:</strong> @Context.Session.GetString("DialogText")
	</div>
	Context.Session.Remove("DialogText");

}

<h2>Edytuj swoje dane</h2>

<form asp-action="Edit">
	<div class="form-horizontal">
		<h4>Twój numer kierowcy: @Model.ID</h4>
		<hr />
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<input type="hidden" asp-for="ID" />
		<div class="form-group">
			<label asp-for="Imie" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="Imie" class="form-control" />
				<span asp-validation-for="Imie" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Nazwisko" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="Nazwisko" class="form-control" />
				<span asp-validation-for="Nazwisko" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-md-2">Twój samochód</label>
			<div class="col-md-10">
				<select asp-for="SamochodID" class="form-control" asp-items="ViewBag.SamochodID"></select>
				<span asp-validation-for="SamochodID" class="text-danger"></span>
				<a asp-action="Create" asp-controller="Samochody" class="btn btn-default">Dodaj nowy samochód</a><br />
				@Html.ActionLink("Edytuj dane swojego samochodu", "Edit", "Samochody", new { id = Model.SamochodID }, new { @class = "btn btn-default" })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Zapisz zmiany" class="btn btn-success" />
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MalaFirmaTaxi/Views/Kierowcy/Index.cshtml
@model IEnumerable<MalaFirmaTaxi.Models.Kierowca>

@{
	ViewData["Title"] = "Kierowcy";
}

<h2>Kierowcy</h2>

<p>
	<a asp-action="Create">Zarejestruj nowego kierowcę</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>Numer</th>
			<th>Imię</th>
			<th>Nazwisko</th>
			<th>Samochód</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.ID)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Imie)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Nazwisko)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Samochod.Nazwa)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.ID">Edytuj</a> |
					<a asp-action="Details" asp-route-id="@item.ID">Szczegóły</a> |
					<a asp-action="Delete" asp-route-id="@item.ID">Usuń</a>
				</td>
			</tr>
		}
	</tbody>
</table>