MalaFirmaTaxi/Controllers/LokalizacjeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MalaFirmaTaxi.Data;
using MalaFirmaTaxi.Models;
using Microsoft.AspNetCore.Http;

namespace MalaFirmaTaxi.Controllers
{
    public class LokalizacjeController : Controller
    {
        private readonly TaxiContext _context;

        public LokalizacjeController(TaxiContext context)
        {
            _context = context;    
        }

        // GET: Lokalizacjas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Lokalizacje.ToListAsync());
        }

        // GET: Lokalizacjas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lokalizacja = await _context.Lokalizacje
                .SingleOrDefaultAsync(m => m.ID == id);
            if (lokalizacja == null)
            {
                return NotFound();
            }

            return View(lokalizacja);
        }

        // GET: Lokalizacjas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lokalizacjas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Ulica,Numer,Miasto,DlugoscGeogr,SzerokoscGeogr")] Lokalizacja lokalizacja)
        {
            if (ModelState.IsValid)
            {
	            if (LokalizacjaExists(lokalizacja))
	            {
		            HttpContext.Session.SetString("AlertText", "W bazie danych istnieje już podana lokalizacja");
		            return View(lokalizacja);
	            }
				_context.Add(lokalizacja);
                await _context.SaveChangesAsync();
				//return RedirectToAction("Create","Zlecenia");
				HttpContext.Session.SetString("DialogText", "Dodano nową lokalizację");
				return Redirect(HttpContext.Session.GetString("RedirectFromLokalizacja"));
            }
            return View(lokalizacja);
        }

        // GET: Lokalizacjas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lokalizacja = await _context.Lokalizacje.SingleOrDefaultAsync(m => m.ID == id);
            if (lokalizacja == null)
            {
                return NotFound();
            }
            return View(lokalizacja);
        }

        // POST: Lokalizacjas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Ulica,Numer,Miasto,DlugoscGeogr,SzerokoscGeogr")] Lokalizacja lokalizacja)
        {
            if (id != lokalizacja.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lokalizacja);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LokalizacjaExists(lokalizacja.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(lokalizacja);
        }

        // GET: Lokalizacjas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lokalizacja = await _context.Lokalizacje
                .SingleOrDefaultAsync(m => m.ID == id);
            if (lokalizacja == null)
            {
                return NotFound();
            }

            return View(lokalizacja);
        }

        // POST: Lokalizacjas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lokalizacja = await _context.Lokalizacje.SingleOrDefaultAsync(m => m.ID == id);
            _context.Lokalizacje.Remove(lokalizacja);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool LokalizacjaExists(int id)
        {
            return _context.Lokalizacje.Any(e => e.ID == id);
        }

	    private bool LokalizacjaExists(Lokalizacja lokalizacja)
	    {
		    return _context.Lokalizacje.Any(e => e.Ulica == lokalizacja.Ulica && e.Numer == lokalizacja.Numer);
	    }
	}
}

MalaFirmaTaxi/Views/Zlecenia/Create.cshtml
@model MalaFirmaTaxi.Models.Zlecenie

@{
	ViewData["Title"] = "Nowe zlecenie";
}

<h2>Dodaj nowe zlecenie</h2>

<form asp-action="Create">
	<div class="form-horizontal">
		<hr />
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<label class="col-md-2 control-label">Klient</label>
			<div class="col-md-10">
				<select asp-for="KlientID" class="form-control" asp-items="ViewBag.KlientID">
					<option value="">-- Wybierz klienta --</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Kierowca</label>
			<div class="col-md-10">
				<select asp-for="KierowcaID" class="form-control" asp-items="ViewBag.KierowcaID">
					<option value="">-- Wybierz kierowcę --</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Koszt kursu</label>
			<div class="col-md-10">
				<input asp-for="Koszt" class="form-control" />
				<span asp-validation-for="Koszt" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Lokalizacja startowa:</label>
			<div class="col-md-10">
				<select asp-for="LokalizacjaStartID" class="form-control" asp-items="ViewBag.LokalizacjaStartID">
					<option value="">-- Wybierz start --</option>
				</select>
				@Html.ActionLink("Dodaj nową lokalizację","Create","Lokalizacje")
			</div>

		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Lokalizacja docelowa:</label>
			<div class="col-md-10">
				<select asp-for="LokalizacjaCelID" class="form-control" asp-items="ViewBag.LokalizacjaCelID">
					<option value="">-- Wybierz cel --</option>
				</select>
				@Html.ActionLink("Dodaj nową lokalizację", "Create", "Lokalizacje")
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Liczba pasażerów</label>
			<div class="col-md-10">
				<input asp-for="LiczbaOsob" class="form-control" />
				<span asp-validation-for="LiczbaOsob" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Dodaj" class="btn btn-default" />
			</div>
		</div>
	</div>
</form>

<div>
	<a asp-action="Index">Powrót do listy zleceń</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MalaFirmaTaxi/Views/Zlecenia/CreateByAnonim.cshtml
@using Microsoft.AspNetCore.Http
@model MalaFirmaTaxi.Models.Zlecenie

@{
	ViewData["Title"] = "Nowe zlecenie";
}

@if (Context.Session.GetString("DialogText") != null)
{
	<div class="alert alert-success">
		<strong>Sukces!</strong> @Context.Session.GetString("DialogText")
	</div>
	Context.Session.Remove("DialogText");
}

<h2>Dodaj nowe zlecenie</h2>

<form asp-action="CreateByAnonim">
	<div class="form-horizontal">
		<hr />
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<label class="col-md-2 control-label">Klient</label>
			<div class="col-md-10">
				<select asp-for="KlientID" class="form-control">
					<option selected="selected" value=@Context.Session.GetString("KlientID")>@Context.Session.GetString("KlientFullName")</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Lokalizacja startowa:</label>
			<div class="col-md-10">
				<select asp-for="LokalizacjaStartID" class="form-control" asp-items="ViewBag.LokalizacjaStartID">
					<option value="">-- Wybierz start --</option>
				</select>
				<a asp-action="Create" asp-controller="Lokalizacje">Dodaj nową lokalizację</a>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Lokalizacja docelowa:</label>
			<div class="col-md-10">
				<select asp-for="LokalizacjaCelID" class="form-control" asp-items="ViewBag.LokalizacjaCelID">
					<option value="">-- Wybierz cel --</option>
				</select>
				<a asp-action="Create" asp-controller="Lokalizacje">Dodaj nową lokalizację</a>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Liczba pasażerów</label>
			<div class="col-md-10">
				<input asp-for="LiczbaOsob" class="form-control" value="1" />
				<span asp-validation-for="LiczbaOsob" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Dodaj" class="btn btn-default" />
			</div>
		</div>
	</div>
</form>

<div>
	@if (Context.Session.GetString("RedirectFromZlecenie") != null)
	{
	<a asp-route=@Context.Session.GetString("RedirectFromZlecenie")>Powrót</a>
	}
	else
	{
	<a asp-action="Index">Powrót do listy</a>
	}
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MalaFirmaTaxi/Views/Zlecenia/CreateByKlient.cshtml
@using Microsoft.AspNetCore.Http
@model MalaFirmaTaxi.Models.Zlecenie

@{
	ViewData["Title"] = "Nowe zlecenie";
}
@if (Context.Session.GetString("AlertText") != null)
{
	<div class="alert alert-danger">
		<strong>Błąd:</strong> @Context.Session.GetString("AlertText")
	</div>
	Context.Session.Remove("AlertText");
}

@if (Context.Session.GetString("DialogText") != null)
{
	<div class="alert alert-success">
		<strong>Sukces!</strong> @Context.Session.GetString("DialogText")
	</div>
	Context.Session.Remove("DialogText");
}

<h2>Dodaj nowe zlecenie</h2>

<form asp-action="CreateByKlient">
	<div class="form-horizontal">
		<hr />
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<label class="col-md-2 control-label">Klient</label>
			<div class="col-md-10">
				<select asp-for="KlientID" class="form-control">
					<option selected="selected" value="@Context.Session.GetString("KlientID")">@Context.Session.GetString("KlientFullName")</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Lokalizacja startowa:</label>
			<div class="col-md-10">
				<select asp-for="LokalizacjaStartID" class="form-control" asp-items="ViewBag.LokalizacjaStartID">
					<option value="">-- Wybierz start --</option>
				</select>
				<a asp-action="Create" asp-controller="Lokalizacje">Dodaj nową lokalizację</a>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Lokalizacja docelowa:</label>
			<div class="col-md-10">
				<select asp-for="LokalizacjaCelID" class="form-control" asp-items="ViewBag.LokalizacjaCelID">
					<option value="">-- Wybierz cel --</option>
				</select>
				<a asp-action="Create" asp-controller="Lokalizacje">Dodaj nową lokalizację</a>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">Liczba pasażerów</label>
			<div class="col-md-10">
				<input asp-for="LiczbaOsob" class="form-control" value="1" />
				<span asp-validation-for="LiczbaOsob" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Dodaj" class="btn btn-default" />
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MalaFirmaTaxi/Views/Zlecenia/Delete.cshtml
@model MalaFirmaTaxi.Models.Zlecenie

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zlecenie</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.Koszt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Koszt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LiczbaOsob)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LiczbaOsob)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Kierowca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Kierowca.Imie)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Klient)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Klient.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LokalizacjaCel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LokalizacjaCel.Miasto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LokalizacjaStart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LokalizacjaStart.Miasto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

MalaFirmaTaxi/Views/Zlecenia/Details.cshtml
@model MalaFirmaTaxi.Models.Zlecenie
@{
    ViewData["Title"] = "Szczegóły wybranego zlecenia";
}

<h2>Zlecenie nr @Model.ID</h2>

@if (Model.Transakcje != null)
{
	<table class="table">
		<tr>
			<th>Numer</th>
			<th>Kierowca</th>
			<th>Data i godzina</th>
			<th>Lokalizacja</th>
			<th>Rodzaj</th>
			<th>Uwagi</th>
		</tr>

		@foreach (var item in Model.Transakcje.OrderBy(i => i.StempelCzasu))
		{
			string selectedRow = "";
			if (item.ID == (int?)ViewData["TransakcjaID"])
			{
				selectedRow = "success";
			}
			<tr class="@selectedRow">
		
				<td>
					@item.ID
				</td>
				<td>
					@item.Kierowca.FullName
				</td>
				<td>
					@item.StempelCzasu
				</td>
				<td>
					@item.Lokalizacja.Adres
				</td>
				<td>
					@item.Rodzaj
				</td>
				<td>
					@item.Uwagi
				</td>
			</tr>
		}

	</table>
}
<div>
    <a asp-action="Index">Powrót do listy wszystkich zleceń</a>
</div>

MalaFirmaTaxi/Views/Zlecenia/Index.cshtml
@model IEnumerable<MalaFirmaTaxi.Models.Zlecenie>

@{
    ViewData["Title"] = "Index";
}

<h2>Zlecenia</h2>

<p>
    <a asp-action="Create">Dodaj nowe zlecenie</a>
</p>
<table class="table">
    <thead>
    <tr>
	    <th>Numer</th>
	    <th>Kierowca</th>
	    <th>Klient</th>
	    <th>Start</th>
	    <th>Cel</th>
	    <th>Koszt</th>
	    <th>Liczba osób</th>
	    <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => item.ID)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Kierowca.FullName)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Klient.FullName)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.LokalizacjaStart.Adres)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.LokalizacjaCel.Adres)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Koszt)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.LiczbaOsob)
		</td>
		<td>
			<a asp-action="Edit" asp-route-id="@item.ID">Edytuj</a> |
			<a asp-action="Details" asp-route-id="@item.ID">Szczegóły</a>
		</td>
	</tr>
}
    </tbody>
</table>